<?php  $this->load->view('website/inc/main_header'); ?>
   <body class="body-2">
      <div class="w-embed w-iframe">
        
      </div>
      <?php  $this->load->view('website/inc/top_header'); ?>
      <div class="container-fluid" style="padding: 0 10%;">
            <section style="text-align:left;">
               <img class="image-about" src="<?php echo base_url(); ?>resource_asset/terms.png">
            <h1><strong>Terms of Service</strong></h1>
            
<address>
<p>This document is an electronic record in terms of Information Technology Act, 2000 (“IT Act, 2000”), the applicable rules there under and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

<p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access to or usage of www.medikamart.in website.</p>

<p>The domain name www.medikamart.in including the related website and web application as well as the seller portal seller.Medikamartsolutions.com (hereinafter referred to as “Platform”) is owned and operated by Medikamart Healthcare Solutions Private Limited (hereinafter referred to as 'Medikamart’'), a company incorporated under the Companies Act, 1956, with its registered office at 86-B, Deven Bagan, Tinplate, Golmuri, Jamshedpur - 831003. Jharkhand.</p>


<p>For the purpose of the Terms of Use (hereinafter referred to as “ToU”), wherever the context so requires, ‘you’ and ‘your’ shall relate to any natural or legal person who has agreed to become a seller on the Platform by providing registration data while registering on the Platform using computer systems. The word ‘user’ shall collectively imply a seller, a buyer, and any visitor on the Platform and the terms ‘we’, ‘us’ and ‘our’ shall mean Medikamart.</p>

<p>Your use of the Platform and the features therein is governed by the following terms and conditions (ToU) including applicable policies available on the Platform, notifications and communications sent to you on the Platform which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such a transaction. By mere use of the Platform you shall be contracting with Medikamart, and these terms and conditions including the policies constitute your binding obligations to Medikamart.</p>

<p>When you use any current or future services provided by us through the Platform you will be subject to the rules, guidelines, policies, terms and conditions applicable to such services and they shall be deemed incorporated into the ToU and considered a part and parcel of the ToU. We reserve the right, at our sole discretion, to change, modify, add, or remove portions of the ToU at any time. We will notify you through any of the communication modes as mentioned in this ToU in case of any changes or updates to the ToU that materially impact your use of the Platform.  Your continued use of the Platform following the changes or updates will mean that you accept and agree to the revisions. As long as you comply with the ToU, we grant you a personal, non-exclusive, non-transferable, and limited privilege to enter and use the Platform.</p>

<p>ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT WITH ALL THE TERMS AND CONDITIONS UNDER THE TOU. PLEASE READ THE TOU CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting the ToU, you also accept and agree to be bound by all of Medikamart’s policies applicable to you, as amended, from time to time.</p>

<h6><b>Seller Eligibility</b></h6>

<p>The use of the Platform is available only to persons who can form legally binding contracts under the Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you shall not register as a seller on the Platform, transact or use the Platform. Medikamart reserves the right to terminate your registration and/or refuse you access to the Platform if it is brought to Medikamart’s notice or discovered that you are under the age of 18 years. If you register as a business entity, you represent that you are duly authorized by the business entity to accept the ToU and you have the authority to bind the business entity to the ToU.</p>

<h6><b>Your Account and Registration Obligations</b></h6>

<p>In the course of your use of the Platform, you agree to furnish your details and information as requested by us from time to time. You shall remain responsible for maintaining confidentiality of this information, as well as your display name, login and password details. You agree that if you provide any information which is untrue, inaccurate, not current, or incomplete or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current, incomplete, or not in accordance with the ToU, we shall have the right to suspend or terminate your account on the Platform or indefinitely block you from accessing the Platform.</p>

<h6><b>Communications</b></h6>

<p>When you use the Platform or send emails, other data, information, or communication to us, you agree and understand that you are communicating with us through electronic records and you consent to receive communications via electronic records from us periodically or as and when required. We may communicate with you by email or any other mode of communication, electronic or otherwise.</p>

<h6><b>Platform for Transaction and Communication</b></h6>

<p>The Platform is a platform that users utilize to independently meet and interact with one another for their transactions. Medikamart is not and cannot be a party to any transaction or dispute between users on the Platform.</p>

<h6><b>Consequently:</b></h6>

<p>1.  All commercial/contractual terms are offered by you and agreed upon between you and buyers alone. The commercial/contractual terms include (without limitation) price, shipping costs, payment methods and terms, date, period, and mode of delivery, and warranties and after-sales services related to products and services. Medikamart does not determine, advice, have any control, or in any way involve itself in the offering or acceptance of such commercial/contractual terms between you and buyers.</p>

<p>2.  Medikamart does not make any representations or warranties regarding specifics (such as quality, value, and salability) of the products or services proposed to be sold, offered to be sold or purchased on the Platform. Medikamart does not implicitly or explicitly support or endorse the sale or purchase of any products and services on the Platform. Medikamart accepts no liability for any errors or omissions of third parties in relation to the products and services.</p>

<p>3.  Medikamart is not responsible for any non-performance or breach of any contract between you and buyers. Medikamart cannot and does not guarantee that you and buyers concerned will perform transaction(s) concluded on the Platform. Medikamart shall not and is not required to mediate or resolve disputes or disagreements between you and buyers.</p>

<p>4.  Medikamart does not make any representations or warranties regarding item-specifics (such as legal title, creditworthiness, identity, etc.) of any of its users. You are advised to independently verify the bona fides of any particular buyer you choose to deal with on the Platform and use your best judgment in that regard.</p>

<p>5.  Medikamart does not at any point in time during a transaction between you and a buyer on the Platform come into or take possession of any of the products or services offered by you, gain title to or have any rights or claims over the products or services offered by you to the buyer.</p>

<p>6.  At no time shall Medikamart hold any right/title to or interest in the items nor have any obligations or liabilities with respect to such a contract. Medikamart is not responsible for unsatisfactory or delayed performance of services, damages, or delays as a result of items which are out of stock, unavailable, or back-ordered.</p>

<p>7.  The Platform is only a platform that can be utilized by you to reach a larger customer base to sell items or services. Medikamart only provides a platform for communication and it is agreed that the contract for sale of any products or services shall be a strictly bipartite contract between you and the buyer.</p>

<p>8.  You release and indemnify Medikamart and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the users on the Platform and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, Medikamart cannot control the information provided by other users which is made available on the Platform. You may find other user's information to be offensive, harmful, inaccurate or deceptive. Please use caution and practice safe trading when using the Platform. Please note that there may be risks in dealing with underage persons or people acting under false pretence.</p>

<h6><b>Use of the Platform</b></h6>

<p>You agree and understand that Medikamart and the Platform merely provide hosting services to its registered users and persons browsing/visiting the Platform. All items advertised / listed and the contents therein are advertised and listed by registered users and are third party user generated contents. Medikamart shall bear no responsibility or liability in relation to or arising out of third party user generated content. Medikamart neither originates nor initiates the transmission nor selects the sender and receiver of the transmission nor selects nor modifies the information contained in the transmission.  Medikamart is merely an intermediary and does not interfere in the transaction between buyers and sellers.</p>

<p><b>You agree, undertake and confirm that your use of the Platform shall be strictly governed by the following binding principles:</b></p>

<p>1.  You shall not host, display, upload, modify, publish, transmit, update or share any information which:</p>

<p>(a) belongs to another person and over which you have no right;</p>

<p>(b) is grossly harmful, harassing, blasphemous, defamatory, bigotry, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating to or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever, or unlawfully threatening or harassing, including but not limited to ‘indecent representation of women’ within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;</p>

<p>(c) is false, inaccurate  or misleading in any way;</p>

<p>(d) is patently offensive to the online community, such as sexually explicit content or content that promotes obscenity, paedophilia, racism, bigotry, hatred, or physical harm of any kind against any group or individual;</p>

<p>(e) harasses or advocates harassment of another person;</p>

<p>(f) involves the transmission of ‘junk mail’, ‘chain letters’, unsolicited mass mailing, or ‘spamming’;</p>

<p>(g) promotes illegal activity or conduct that is abusive, threatening, obscene, defamatory, or libelous;</p>

<p>(h) infringes upon or violates any third party's rights [including but not limited to intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address, or phone number) or rights of publicity];</p>

<p>(i) promotes an illegal or unauthorized copy of another person's copyrighted work (see “Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material) such as providing pirated computer programs or links, information to circumvent manufacturer-installed copy-protect devices, or pirated music or links to pirated music files;</p>

<p>(j) contains restricted or password-only access pages, hidden pages or images or URLs leading to any other pages (those not linked to or from another accessible page);</p>

<p>(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</p>

<p>(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, providing or creating computer viruses;</p>

<p>(m) contains unauthorized videos, photographs or images of another person (whether a minor or an adult);</p>

<p>(n) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform, profiles, blogs, communities, account information, bulletins, friend requests, or other areas of the Platform, or solicits passwords or personal identifying information for commercial or unlawful purposes from other users on the Platform;</p>

<p>(o) engages in commercial activities and/or sales such as contests, sweepstakes, barter, advertising, pyramid schemes, or the buying or selling of ‘virtual’ items related to the Platform without our prior written consent.</p>

<p>Throughout the ToU, Medikamart’s prior written consent means a communication coming from Medikamart’s Legal Department in response to your request and specifically addressing the activities or conduct for which you have sought authorization;</p>

<p>(p) solicits gambling or engages in any gambling activity which we, at our sole discretion, believe is or could be construed as being illegal;</p>

<p>(q) interferes with another’s use and enjoyment of the Platform;</p>

<p>(r) refers to any website/URL which, at our sole discretion, contains material that is inappropriate for the Platform or any other website and content that is prohibited or violates the letter and spirit of ToU;</p>

<p>(s) harms minors in any way;</p>

<p>(t) infringes any patent, trademark, copyright, proprietary rights, third-party’s trade secrets, rights of publicity, or privacy, is fraudulent, or involves the sale of counterfeit or stolen items;</p>

<p>(u) violates any law for the time being in force;</p>

<p>(v) deceives or misleads the addressee/ users about the origin of messages or communicates any information which is grossly offensive or menacing in nature;</p>

<p>(w) impersonates another person;</p>

<p>(x) contains software viruses or any other computer codes, files, or programs designed to interrupt, destroy, or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs, or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept, or expropriate any system, data, or personal information;</p>

<p>(y) threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any offense or prevents investigation of any offense or is insulting any other nation;</p>

<p>(z) shall, directly or indirectly, offer or attempt to offer trade or attempt to trade in any item which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force;</p>

<p>(aa) shall create liability for us or cause us to lose (in whole or part) the services of our Internet Service Provider (“ISPs”) or other suppliers.</p>

<p>2. You shall not use any ‘deep-link’, ‘page-scrape’, ‘robot’, ‘spider’, automatic device, program, algorithm, methodology, or any similar or equivalent manual process to access, acquire, copy, monitor any portion of the Platform or content or in any way reproduce, or circumvent the navigational structure, presentation of the Platform, or any content to obtain or attempt to obtain any material, documents, or information through any means not purposely made available through the Platform. We reserve our right to bar any such activities.</p>

<p>3.  You shall not attempt to gain unauthorized access to any portion or feature of the Platform, other systems, networks connected to the Platform, server, computer, network, or the services offered on or through the Platform by hacking, password ‘mining’, or any other illegitimate means.</p>

<p>4.  You shall not probe, scan or test the vulnerability of the Platform or any network connected to the Platform or breach the security, authentication measures on the Platform or any network connected to the Platform. You may not reverse look-up, trace or seek to trace information on any other user of or visitor to Platform (including any account on the Platform that is not owned by you) or to its source or exploit the Platform, any service, information made available, or offered by or through the Platform in any way where the purpose is to reveal any information (including but not limited to personal identification or information other than your own information) provided by the Platform.</p>

<p>5.  You shall not make any negative, denigrating, or defamatory statement(s)/comment(s) about us, the brand name or domain name used by us, including the terms Medikamart, or otherwise engage in any conduct or action that might tarnish the image or reputation of Medikamart or sellers on the platform or otherwise tarnish or dilute any Medikamart trade mark, service marks, trade name and/or goodwill associated with such trade, service marks or trade name as may be owned or used by us. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Platform or Medikamart’s systems, networks, or any systems or networks connected to Medikamart.</p>

<p>6.  You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Platform, any transaction being conducted on the Platform or any other person’s use of the Platform.</p>

<p>7.  You shall not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message, transmittal you send to us on or through the Platform, or any service offered on or through the Platform. You may not pretend that you are or represent someone else or impersonate any other individual or entity.</p>

<p>8.  You may not use the Platform or any content for any purpose that is unlawful or prohibited by the ToU or to solicit the performance of any illegal activity or other activity which infringes the rights of Medikamart and/or others.</p>

<p>9.  You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000, and the rules thereunder as applicable and amended from time to time and also all applicable domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Integrated Goods and Services Tax Act, Central Goods and Services Tax Act, relevant State Goods and Services Tax Act or Union Territories Goods and Services Tax Act and Custom Duty, Local Levies as may be applicable) and obtain the necessary licences and permits regarding your use of our Platform, service and/or tools and your listing, purchase, solicitation of offers to purchase, and sale of items or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force. In particular you shall ensure that if any of your items listed on the Platform qualifies as an "Antiquity" or "Art treasure" as defined in the Act ("Artwork"), you shall indicate that such Artwork is "non-exportable" and sold subject to the provisions of the Antiquities and Art Treasures Act, 1972, and shall ensure that it is not delivered to any buyer at any place outside India.</p>

<p>10. Solely to enable us to use the information you provide us with and so that we do not violate any rights you might have in your information, you agree to grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, and sub-licensable (through multiple-tiers) right to exercise the copyright, publicity or database rights or any other rights you have in your information for any current or future promotional or advertising related activities and any business purposes of Medikamart. We will only use your information in accordance with this ToU and our Privacy Policy.</p>

<p>11. From time to time you shall be responsible for providing information relating to the items or services proposed to be sold by you. In this connection, you undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such items or services so as to mislead other users on the Platform in any manner.</p>

<p>12. You shall not engage in advertising or solicitation of other sellers on the Platform to buy or sell any products or services, including but not limited to products or services related to what is displayed on the Platform. You may not transmit any chain letters or unsolicited commercial or junk email to other users acquired/via the Platform. It shall be a violation of the ToU to use any information obtained from the Platform in order to harass, abuse, or harm others or contact, advertise and sell to or solicit persons other than those who have chosen to buy from you. You understand that we have the right at all times to disclose any information (including the identity of the persons who have provided information or material on the Platform) as necessary to satisfy any law, regulation, or valid governmental request. This may include, without limitation, disclosure of the information in connection with the investigation of an alleged illegal activity or its solicitation and/or response to a lawful court order or subpoena. In addition, we can (and you hereby expressly authorized us to) disclose any information about you to law enforcement or other government officials as we, at our sole discretion, deem necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury. We reserve the right, but have no obligation, to monitor the material posted on the Platform. Medikamart shall have the right, at its sole discretion, to remove any content that violates or is alleged to violate any applicable law or either the spirit or letter of the ToU. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIAL YOU POST ON THE WEBSITE AND YOUR INDEPENDENT COMMUNICATION WITH THE BUYERS AND OTHER SELLERS, REGARDLESS OF FORM. Please be advised that such content posted does not reflect Medikamart’s views. In no event shall Medikamart assume or have any responsibility or liability for any content posted on the Platform or claims, damages, or losses resulting from its use and/or appearance of it on the Platform. You hereby represent and warrant that you have necessary rights to all the content you provide and all information it contains and that such content shall not infringe any proprietary or other rights of third parties or contain any misleading, libelous, tortious, or otherwise unlawful information.</p>

<p>13. Your correspondence or business dealings with or participation in the promotion of advertisers on or through the Platform (including payment and delivery of related products or services, any other terms, conditions, warranties, or representations associated with such dealings) are solely between you and such advertisers. We shall not be responsible or liable for any loss or damage of any sort incurred as a result of such dealings or the presence of such advertisers on the Platform.</p>

<p>14. It is possible that other users (including unauthorized persons or ‘hackers’) may post or transmit offensive or obscene material on the Platform and that you may be involuntarily exposed to such material. It is also possible for others to obtain personal information about you due to your use of the Platform and use such information to harass or injure you. We do not approve of such unauthorized uses but by using the Platform, you acknowledge and agree that we are not responsible for the use of any personal information that you publicly disclose or share with others on the Platform. Please carefully select the type of information that you publicly disclose or share with others on the Platform.</p>

<p>15. Medikamart shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group(s) of people, intentionally or unintentionally, in DoS (denial of service) / DDoS (Distributed Denial of Services).</p>

<p><b>Selling</b></p>

<p>As a registered seller, you shall list item(s) for sale on the Platform in accordance with the policies which are incorporated by way of reference in this ToU. You must be legally able to sell the item(s) you list for sale on our Platform and must have all the necessary licences and permits required for such sale. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics,  pictures or videos that describe your item for sale. All items must be listed in an appropriate category on the Platform. All listed items must be kept in stock for successful fulfilment of sales. The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amount that you may have received from the buyer. You agree not to list a single product in multiple quantities across various categories on the Platform. Medikamart reserves the right to delete such multiple listings of the same product listed by you in various categories.</p>

<p>For Food and Nutrition category, seller shall adhere to the minimum balance shelf life norms as provided at the link here</p>

<p><b>Compliance on selling of goods/services</b></p>

<p>You shall also ensure full compliance with the provisions of Integrated Goods and Services Tax (IGST), Central Goods and Services Tax (CGST) and Union Territory Goods and Services Tax (UTGST) or State Goods and Services Tax (SGST) in respect of the goods/services supplied by you.</p>

<p>It is your responsibility to charge appropriate goods and services taxes on the supplies effected and remittance of the same to the Government.  Medikamart shall not be responsible for any deficiency and/ or omission on your part.</p>

<p>Pursuant to the tax collection at source provisions under IGST, CGST and/UTGST or SGST, the portal would collect tax collection at source at applicable rates on net value of taxable supplies made through the portal and remit to the appropriate Government.</p>

<p>In case of any mismatches on account of tax collection at source, you shall be required to provide all relevant information to Medikamart to correspond with the relevant authorities and also in case of any liability accruing on account of omission shall be your obligation to pay such deficit.</p>

<p>You shall be required to provide the corresponding Harmonised System Nomenclature (HSN) code number for every product listing . In the event that you do not provide the HSN code number  that particular product will be delisted and you will no longer be able to sell the product on our platform.</p>

<p>You shall also be required to provide your GSTIN , without which we will not be able to raise an invoice on you. In the event that you do not provide your GSTIN number, transaction on your account will be blocked and orders will not be processed on your account. In the event of you providing your Input Service Distributor Registration Number, Medikamart would be issuing an invoice to the ISD GST registration number as furnished by you.  It is your responsibility to undertake the necessary compliance required in respect of the said ISD registration number.</p>

<p>In the event of any conflict between the terms of this clause and any other clause in these terms of use, the provisions of this clause will prevail.</p>

<p><b>Content Posted on the Platform</b></p>

</p>All text, graphics, seller interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork, notes, messages, emails, billboard postings, drawings, profiles, opinions, ideas, images, videos, audio files, other material or information (collectively ‘Content’) are third-party generated Content and Medikamart has no responsibility or liability over such third-party generated Content as Medikamart is merely an intermediary for the purposes of this ToU. Except as expressly provided in the ToU, no part of the Platform including the Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including ‘mirroring’) to any other computer, server, website or other medium for publication, distribution or any commercial enterprise without Medikamart’s prior written consent.</p>

</p><b>You may use the information on the products and services made available on the Platform for downloading provided you:</b></p>

<p>(1) do not remove any proprietary notice language in all copies of such Content;</p>

<p>(2)  use such Content only for your personal, non-commercial informational purpose and do not  copy or post such information on any networked computer or broadcast it to any media;</p>

<p>(3) make no modifications to any Content; and</p>

<p>(4) do not make any additional representations or warranties relating to the Content.</p>

<p>You shall be responsible for the Content posted or transmitted on the Platform by You. The Content will become our property and you grant us the worldwide, perpetual, royalty free and transferable rights in such content. We shall be entitled to, consistent with our privacy policy as adopted in accordance with applicable law,  use the Content or any of its elements for any type of purpose forever, including, but not limited to, promotional and advertising purposes in any media, whether now known or hereafter devised or the creation of derivative work. You agree that any content you post may be used by us, consistent with this TOU, and you are not entitled to any payment or other compensation for such use.</p>

<p><b>Limited License</b></p>

<p>Medikamart grants seller a limited, non-transferable, non-exclusive, non-sub licensable, non-assignable and personal license to use "Powered by Medikamart" and/or “Medikamart.in” name and/or logo on seller’s invoice for transactions concluded on the Platform. Further, Medikamart grants seller a limited, non-transferable, non-exclusive, non-sublicensable, non-assignable and personal license to use “Medikamart.com” name and/or logo on packing material used by seller for delivery of Products sold on the Platform.</p>

<p><b>Types of Sellers</b></p>

<p><b>All registered sellers are categorized into following tiers:</b></p>

<p>Gold</p>
<p>Silver</p>
<p>Bronze</p>
 

<p><b>This is done basis following criteria</b></p>

<p>sales achieved by sellers (revenues and units)
fulfillment experience provided to customers (breaches and cancellations)
Percentage of local/zonal shipment out of your overall shipment</p> ​​​​​​​
<p>percentage of overall shipments supplied in the same zone to customers by the seller
customer feedback against the products sold by such sellers (returns and ratings), etc.</p>
 

<p><b>The thresholds for each of these criteria are transparently listed on https://seller.Medikamartsolution.com. Basis the tier, sellers get benefits including the following:</b></p>

<p>rebate in commissions and shipping fees etc.</p>
<p>account management support</p>
<p>faster payments</p>
 

<p>Medikamart reserves the right to revise the categories, criteria, and benefits to promote healthy competition amongst the sellers so that their performance lead to better customer experience on the Platform.</p>

<p><b>Payment</b></p>

<p>1. Transactions, transaction price and all commercial terms such as delivery, dispatch of products  and/or services are as per principal to principal bipartite contractual obligations between sellers and buyers and the payment facility is merely used by sellers and buyers to facilitate the completion of transactions. Use of the payment facility shall not render Medikamart liable or responsible for non–delivery, non-receipt, non-payment, damage, breach of representations and warranties, non-provision of after-sales or warranty services or fraud as regards the products and/or services listed on the Platform.</p>

<p>2. You have specifically authorized Medikamart or its service providers to collect, process, facilitate, and remit payments and/or the transaction price electronically or through cash on delivery (CoD) to and from buyers in respect of transactions through payment facility. Your relationship with Medikamart is on a principal to principal basis and by accepting the ToU, you agree that Medikamart is an independent contractor for all purposes and does not have control of or liability for the products or services that are listed on the Platform and paid for by using the payment facility. Medikamart does not guarantee the identity of any User nor does it ensure that a buyer or a seller will complete a transaction.</p>

<p>3. You understand, accept, and agree that the payment facility provided by Medikamart is neither a banking nor financial service, but merely a facilitator providing an electronic, automated online electronic payment facility for receiving payment, or cash on delivery (CoD) payment, collection and remittance for transactions on the Platform using the existing authorized banking infrastructure and credit card payment gateway (PG) network. Further, by providing payment facility, Medikamart neither acts as a trustee nor fiduciary with respect to transaction or transaction price.</p>

<p>It is hereby clarified that cash on delivery (COD) option may not be available for select products or categories, at Medikamart’s sole discretion.</p>

<p>4. All online bank transfers from valid bank accounts are processed using the gateway provided by the respective issuing bank that supports payment facility to provide these services to the users. All such online bank transfers on payment facility are also governed by the terms and conditions agreed to between a seller buyer and the respective issuing bank.</p>

<p>Dispatch of products and/or services1.  You, as a seller, shall be required to dispatch the products and/or services for every transaction to the buyer within the time period as provided in the TOU to ensure that the products and/or services are delivered in a timely manner. Further, you will solely be responsible for undertaking transit insurance for products sold by You on the Platform. For avoidance of doubt, Medikamart will not be responsible for undertaking any insurance(s) for products sold by sellers on the Platform</p>

<p>2.  Seller shall provide dispatch details and details of after-sales services related to products and services listed by it on the Platform to Medikamart in such a manner and within a time period as provided in the policies, failing which the transaction shall stand cancelled.</p>

<p>3.  Seller shall dispatch the products and/or services using only an approved delivery channel which provides appropriate ‘proof of dispatch’ & ‘proof of delivery’ (PoDs) documentation. Such PoD documentation relating to delivery should be maintained by a seller for a period of 3 (three) years from the date of dispatch. The PoDs should be furnished to Medikamart on demand within the time frame as notified from time to time.</p>

<p>4.  Seller agrees that the dispatch details shall be true, correct, and duly authorized and shall not be misleading, fraudulent, false, unauthorized, illegal and shall not contain any misrepresentation of facts.</p>

<p>5.  In case a seller fails to provide dispatch details or provides dispatch details not complying with policies, it shall result in consequences as more specifically stated in the TOU and may lead to suspension and/or termination of seller account.</p>

<p>6.  Seller agrees that the transaction price paid by a buyer will be remitted to a seller’s bank account contingent upon the following events:</p>

<p>a) Buyer confirms the delivery of products and/or services in the transaction;</p>

<p>b) Buyer does not take any action on payment facility to confirm delivery within such a time period as provided in the policies despite confirmation of dispatch of products and/or services by a seller to the buyer;</p>

<p>c) Buyer’s refund claim is rejected by Medikamart due to any breach of the ToU, policies, and any applicable law;</p>

<p>Once the transaction is completed by the Seller, the remittance to seller shall be made in accordance with RBI Intermediary Guidelines.</p>

<p><b>Prepaid Payment Instruments</b></p>

<p>Medikamart may, either itself or through third-party service providers, offer prepaid instruments as a payment option for transactions on the Platform to users. Any purchases by buyers on the Platform using the prepaid instruments shall be governed by the following terms and conditions:</p>

<p>Such prepaid instruments may be used to make payments for the products and/or services purchased on the Platform</p>
<p>Such prepaid instruments can be redeemed by buyers by selecting the payment mode as may be provided on the Platform.</p>
<p>Such prepaid instruments cannot be used to purchase other prepaid instruments or gift vouchers.
If the order value exceeds the amount of such prepaid instruments, the balance must be paid by the respective buyer via Credit Card/Debit Card /Internet Banking. COD shall not be available as payment option for such transactions.</p>
<p>If the order value is less than the amount of such prepaid instruments, the outstanding balance (after deduction of order value) will reflect as credit balance for such prepaid instruments.</p>
<p>Prepaid instruments and any unused balance of such prepaid instruments shall expire 1 year from the date of their issue.</p>
<p>Prepaid instruments cannot be redeemed for cash.</p>
<p>Medikamart is not responsible if prepaid instruments are lost, stolen, or used without permission.
Buyers can combine and use a maximum of 3 prepaid instruments per order. They can be combined with promotional codes.</p>
<p>Purchases of prepaid instruments are not eligible for cashback offers.</p>
<p>All sellers on the Platform will accept this prepaid instrument as a payment instrument.</p>
Medikamart will make payments to sellers whose products and/or services have been purchased by buyers redeeming electronic gift vouchers (EGV) as per the guidelines issued by the Reserve Bank of India from time to time.</p>
<p><b>Financial Facilities for customers</b></p>

<p>Medikamart has operationalized tie-ups with multiple partners for providing financial assistance to customers for purchasing products on the platform and thereby enhancing the transaction capability of customers. In pursuance of the same, in the event of the customers opting for the financial assistance program and you duly receiving such amounts from the partners (on behalf of the customers), you hereby agree to assign all receivables from the customer for such transaction. Therefore you hereby agree that without any further action on your part, upon receipt of amount due from such partners, any and all receivables due from the customers shall stand assigned in favour of the partner. You hereby authorize Medikamart to enter into any documentation on your behalf to complete and perfect the assignment. Upon such assignment, the financing partner shall have all the rights as the seller may have had in relation to the collection of receivables from the customer and the customer shall be required to repay the financing partner directly. The lending partner further reserves the right to assign and transfer such receivables under these terms and conditions to an NBFC/financial institution as it may deem fit.</p>

<p><b>Charges</b></p>

<p>Registration on the Platform is free. Medikamart does not charge any fee for browsing/registering on the Platform. However, before you list a product or service for sale through the Platform, we request you to review our fee policy, which is hereby incorporated by reference into this ToU. Medikamart reserves the right to change its fee policy from time to time. In particular, Medikamart may, at its sole discretion, introduce new services and modify some or all of the existing services offered on the Platform. In such an event, Medikamart reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the fee policy shall be posted on the Platform and such changes shall automatically become effective immediately after they are posted on the Platform. Unless otherwise stated, all fees shall be quoted in Indian Rupees (INR) and payable to Medikamart. You shall be solely responsible for compliance with all applicable laws for making payments to Medikamart.</p>

<p>GST /Taxes:  You are responsible for paying all fees associated with the use of the Platform and charges collected in respect of such usage.  You agree to bear any and all applicable taxes, charges, cesses levied thereon (including CGST+SGST/IGST/CGST+UGST and GST cess as may be applicable to the transaction).</p>

<p>1.  A seller agrees that Medikamart may offer to provide express remittance to eligible sellers as per payments settlement policy. Express Remittance shall be subject to RBI Intermediary Guidelines and arrangements/directions of the nodal bank. Medikamart, at its sole discretion, may make such an offer to eligible sellers and the same shall not be construed as a right but only as a privilege. Eligible sellers understand that Medikamart reserves the right to withdraw Express Remittance at any time for any violation of the ToU or Medikamart’s policies and/or failure by the eligible sellers to maintain or comply with the parameters as may be decided by Medikamart from time to time.</p>

<p>2. Invoice generation: A seller expressly agrees that issuing correct and complete invoice is the sole and primary responsibility of a seller. We will assist you with this process by generating an invoice on your behalf.  For us to generate these invoices, we would need a digital image of your signature which will be affixed on the invoice. The invoice shall then be generated and sent to the seller. The seller shall be required to physically sign the invoice, print the invoice and affix the same on the consignment. The invoice generated by Medikamart shall be affixed by the seller on the consignment. Notwithstanding anything else contained in these terms of use, the seller shall be solely liable for any liability which may be imposed by taxation authorities for any discrepancy in the invoices.</p>

<p>A seller expressly agrees that issuing correct and complete invoice is the sole and primary responsibility of a seller. Furthermore, seller shall ensure that invoices state ‘Powered by Medikamart’ and failing to do so, a seller shall be liable to chargebacks (as applicable).</p>

<p>3. In case of any chargebacks levied by the bank, Medikamart shall have the right to deduct such chargebacks from seller remittances, present and future, and a seller’s only remedy will be to discuss and resolve the same with the bank. A seller hereby agrees to extend full co-operation in resolving the chargeback disputes raised by a buyer through the bank and shall provide necessary documentation regarding the transaction to the complete satisfaction of the bank. In case the chargeback is ruled against a seller, Medikamart shall be entitled and authorized to recover the same from the seller to its fullest extent and the bank’s decision shall be final and binding in this regard. In the event Medikamart has made any excess payment to seller inadvertently, such excess payments shall be set-off from any future payments payable by Medikamart to the seller.</p>

<p>4.  Medikamart may delay notifying the payment confirmation, i.e. informing seller to dispatch if Medikamart deems suspicious or a buyer conducts high transaction volumes to ensure safety of the transaction and transaction price. In addition, Medikamart may hold transaction price and not inform seller to dispatch or remit transaction price to law enforcement officials (instead of refunding the same to a buyer) at the request of law enforcement officials or in the event of a buyer being engaged in any form of illegal activity.</p>

<p>5.  Sellers acknowledge that Medikamart will not be liable for any damages, interests, claims etc. resulting from not processing a transaction/transaction price or any delay in processing a transaction/transaction price that is beyond the control of Medikamart.</p>

<p>6. Medikamart shall make payments into the bank account provided by a seller during the seller registration process. Once Medikamart has made payments into such a bank account number, Medikamart shall be discharged of any/all liabilities towards the seller and the seller shall not be eligible for any claims whatsoever.</p>

<p><b>Compliance with Laws:</b></p>

<p>1.  Seller shall comply with all the applicable laws and  obtain all necessary licences and permits applicable to them.</p>

<p>2. In the event of sale of jewellery, seller shall provide hallmark certificate (in accordance with applicable laws) along with the product at the time of delivery. Further, it shall be sole responsibility of the seller to comply with hallmarking or other similar provisions applicable for the sale of jewellery and Medikamart shall not be liable whatsoever for any non-compliance in this regard.</p>

<p>3.  In the event of sale of jewellery, seller shall ensure conducting of buyer KYC in accordance with the prevention of anti-money laundering laws and other applicable laws. Medikamart hereby disclaims any responsibility for conducting Buyer KYC.</p>

<p><b>Product Description</b></p>

<p>Medikamart does not warrant that product description or other content on the Platform is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.</p>

<p><b>Audits</b></p>

<p>Medikamart shall have the right to inspect and audit seller’s records and premises / place of business through itself or through Medikamart approved third party testing agencies. Cost of such audit shall solely be borne by Medikamart unless audit reflects discrepancy in seller accounts / non-compliance with Medikamart’s seller policies, in which case cost of audit shall be borne by the seller.</p>

<p><b>Breach</b></p>

<p>Without limiting other remedies, we may limit your activity, immediately remove your information, warn other users of your actions immediately, temporarily/indefinitely suspend/terminate/block your account and/or refuse you access to the Platform in the event of, including but not limited to, the following:</p>

<p>1. if you breach the ToU, privacy policy or other policies (if any);</p>

<p>2. if we are unable to verify or authenticate any information you provide; or</p>

<p>3. if it is believed that your actions may cause legal liability for you, other users, or us;</p>

<p>We may at any time, at our sole discretion, reinstate suspended sellers. A seller that has been suspended or blocked may not register or attempt to register with us or use the Platform (through itself or any other entity or legal form) in any manner whatsoever until such time that such a seller is reinstated by us. Notwithstanding the foregoing, if you breach the ToU or other rules and policies, we reserve the right to recover any amounts due and owed by you to us and take strict legal action, including but not limited to a referral to the appropriate police or other authorities for initiating criminal or other proceedings against you.</p>

<p><b>Indemnity</b></p>

<p>You shall indemnify and hold harmless Medikamart its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees from any claim, demand, or actions including reasonable attorneys' fees made by any third party or penalty imposed due to or arising out of your breach of the ToU, privacy policy and other policies or your violation of any law, rules, regulations or the rights (including infringement of intellectual property rights) of a third party.</p>

<p><b>Trademark complaint</b></p>

<p>Medikamart respects the intellectual property of others. In case you feel that your trademark has been infringed, you can write to support@medikamart.in</p>

<p><b>Copyright complaint</b></p>

<p>Medikamart respect the intellectual property of others. In case you feel that your work has been copied in any way that constitutes copyright infringement you can write to Medikamart at copyright@Medikamart.in or support@medikamart.in</p>

<p><b>Trademark, Copyright and Restriction</b></p>

<p>The Website is controlled and operated by Medikamart and products are sold by respective registered sellers. All material on the Platform, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks and other intellectual property rights. You must not copy, reproduce, republish, upload, post, transmit, or distribute Medikamart’s or other sellers’ material in any way, including by email or other electronic means and whether, directly or indirectly, you must not assist any other person to do so. Without the prior written consent of the owner, modification or use of the material on any other website/networked computer environment or for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks, and other proprietary rights is prohibited. Any use for which you receive any remuneration, whether money or otherwise, is a commercial use for the purposes of this clause.</p>

<p><b>Limitation of Liability</b></p>

<p>IN NO EVENT SHALL Medikamart BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THE TOU, EVEN IF Medikamart HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.</p>

<p><b>Applicable Law</b></p>

<p>The ToU shall be governed, interpreted, and construed in accordance with the laws of India. The place of jurisdiction shall exclusively be Bangalore.</p>


<p><b>Jurisdictional Issues/Sale in India Only</b></p>

<p>Unless otherwise specified, the material on the Website is presented solely for the purpose of sale in India. Medikamart makes no representation that the material on the Website is appropriate or available for use in other locations/countries other than India. Those who choose to access the Website from other locations/countries other than India do so on their own initiative and Medikamart is not responsible for supply of products/refund for the products ordered from other locations/countries other than India and compliance with local laws, if and to the extent local laws are applicable.</p>

<p><b>Contact Us</b></p>

<p>Please send any comments or questions, including all enquiries not related to trademark and copyright infringement, on the Website to support@medikamart.in</p>

<p><b>Grievance Officer</b></p>

<p>In accordance with the IT Act, 2000, and the rules thereunder, the name and contact details of the grievance officer are provided below:</p>

<p><b>Mr. Santosh Rastogi</b></p>

<p>Medikamart Healthcare Solutions Private Limited</p>

<p>86-B, Deven Bagan, Tinplate, Golmuri, Jamshedpur - 831003, Jharkhand, India.</p>

<p>Phone: NA</p>

<p>Email: support@medikamart.in</p>

<p>Time: Mon – Sat (9:00 – 18:00)</p>
</address>
</section>
            
      </div>
      <?php  $this->load->view('website/inc/footer'); ?>
   </body>
</html>



<style type="text/css">
.image-about{
   width: 40%;
}
.image-team{
   border-radius: 50px;
   height: 100px;
   width: 100px;
}
   .float{
   position:fixed;
   /*width:60px;*/
   font-size: 20px;
   height:60px;
   bottom:40px;
   right:40px;
   background-color:#0C9;
   color:#FFF;
   border-radius:50px;
   text-align:center;
   box-shadow: 2px 2px 3px #999;
}
.my-float{
   margin-top:22px;
}
a:hover{
   color: white;
}
.not-effected:hover{
   color: black;
   text-decoration: none;
}
.not-underline{
   text-decoration: none;
}
</style>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>